### ISSUE TITLE
PACKAGE ICONS: Roadmap before releasing

### ISSUE THREAD

**Issue by marticliment** [marticliment/UniGetUI#2932]
### Roadmap before Package Icons on package lists can be released

 - [x] Force WinGet into caching native CatalogPackage objects
 - [x] Fix the log being flodded by icon information
 - [x] Prevent one icon from being loaded concurrently X times
 - [x] Make icons opt-out on the settings
 - [ ] Better minetype detection?
 - [ ] Resize bigger images?
