### ISSUE TITLE
[ISSUE] UniGetUI updates PowerShell meta-module components twice unless user intervenes

### ISSUE THREAD

**Issue by nogaff** [marticliment/UniGetUI#3003]
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.4-beta1

### Windows version, edition, and architecture

Windows 11 Pro 10.0.26100.2314 x64

### Describe your issue

If a PowerShell meta-module is installed (e.g. _Microsoft.Graph_) which references _n_ other component modules (e.g. _Microsoft.Graph.Groups_, _Microsoft.Graph.Users_, etc), then whenever an update is available for the meta-module, UniGetUI will claim there are _n + 1_ updates available (the meta-module plus each individual component module).

If the user tries to install all available updates, UniGetUI will proceed to update the meta-module first, then each individual component module, even though they have already been updated by the meta-module. In other words, each component module gets updated twice.

I feel like UniGetUI should recognise that the component modules are part of the meta-module and do something to avoid the duplication of updates. That could be any of the following:

1. Hiding the meta-module.
2. Hiding the component modules.
3. Grouping the component modules under the meta-module in some sort of treeview/expander/fieldset so that the user can choose to update the whole meta-module, or individual components, but not both.
4. Rescanning for available updates after a meta-module has been updated and aborting/clearing the individual component module updates if they've already been updated by the meta-module.

### Steps to reproduce the issue

1. Install an older version of the _Microsoft.Graph_ module in PowerShell (latest is 2.25.0 at time of writing):
 `Install-Module Microsoft.Graph -Scope CurrentUser -MaximumVersion 2.24.0`

3. Open UniGetUI and check for updates. It will show 40 updates available, for _Microsoft.Graph_ plus all of its 39 component modules.

4. Leave all updates selected and click the _"Update selected packages"_ button. It will first update the _Microsoft.Graph_ meta-module, including all related component modules, then it will update each component module a second time, individually.

### UniGetUI Log

```text
[21/11/2024 12:42:30]    __  __      _ ______     __  __  ______
                        / / / /___  (_) ____/__  / /_/ / / /  _/
                       / / / / __ \/ / / __/ _ \/ __/ / / // /
                      / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                      \____/_/ /_/_/\____/\___/\__/\____/___/
                          Welcome to UniGetUI Version 3.1.4-beta1
[21/11/2024 12:42:30]
[21/11/2024 12:42:30] Build 71
[21/11/2024 12:42:30] Encoding Code Page set to 850
[21/11/2024 12:42:30] Using built-in UniGetUI Elevator
[21/11/2024 12:42:31] Loaded language locale: en
[21/11/2024 12:42:32] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Chocolatey
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/11/2024 12:42:32] Command vcpkg was not found on the system
[21/11/2024 12:42:32] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: vcpkg
                      █ Enabled: True
                      █ Found: False
                      █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                      █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/11/2024 12:42:32] Command npm was not found on the system
[21/11/2024 12:42:32] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Npm
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/11/2024 12:42:32] Command cargo was not found on the system
[21/11/2024 12:42:32] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Cargo
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/11/2024 12:42:32] Lang files were updated successfully from GitHub
[21/11/2024 12:42:32] Downloaded new icons and screenshots successfully!
[21/11/2024 12:42:33] Command scoop was not found on the system
[21/11/2024 12:42:33] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Scoop
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/11/2024 12:42:33] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Winget
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/11/2024 12:42:33] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: .NET Tool
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: dotnet tool
                      █ Executable path: c:\program files\dotnet\dotnet.exe
                      █ Call arguments: tool
                      █ Version: 
                      █   8.0.404
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/11/2024 12:42:33] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: Pip
                      █ Enabled: False
                      █ THE MANAGER IS DISABLED
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/11/2024 12:42:35] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell7
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: pwsh.exe
                      █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   PowerShell 7.4.6
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/11/2024 12:42:35] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                      █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                      █ Name: PowerShell
                      █ Enabled: True
                      █ Found: True
                      █ Fancy exe name: powershell.exe
                      █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                      █ Call arguments:  -NoProfile -Command
                      █ Version: 
                      █   Name                           Value                                                                                   
                      █   ----                           -----                                                                                   
                      █   PSVersion                      5.1.26100.2161                                                                          
                      █   PSEdition                      Desktop                                                                                 
                      █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                      █   BuildVersion                   10.0.26100.2161                                                                         
                      █   CLRVersion                     4.0.30319.42000                                                                         
                      █   WSManStackVersion              3.0                                                                                     
                      █   PSRemotingProtocolVersion      2.3                                                                                     
                      █   SerializationVersion           1.1.0.1
                      ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[21/11/2024 12:42:35] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[21/11/2024 12:42:36] Dependency .NET Tools Outdated for manager .NET Tool is present
[21/11/2024 12:42:37] Found 13 installed packages from PowerShell7
[21/11/2024 12:42:37] Found 1 installed packages from .NET Tool
[21/11/2024 12:42:37] Found 0 available updates from .NET Tool
[21/11/2024 12:42:37] Ignored updates database was never loaded, so it is going to be loaded now
[21/11/2024 12:42:41] Found 51 installed packages from PowerShell
[21/11/2024 12:42:42] Cached ocon for id=PnP.PowerShell is INVALID (PackageVersion)
[21/11/2024 12:42:42] Cached ocon for id=PnP.PowerShell is INVALID (PackageVersion)
[21/11/2024 12:42:45] Cached ocon for id=WinSCP is INVALID (PackageVersion)
[21/11/2024 12:42:47] Cached ocon for id=WinSCP is INVALID (PackageVersion)
[21/11/2024 12:42:53] Failed to download the PowerShell manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='Microsoft.Graph.CrossDeviceExper...',Version='2.24.0') with status code NotFound
[21/11/2024 12:42:53] No manifest content could be loaded for package Microsoft.Graph.CrossDeviceExper... on manager PowerShell
[21/11/2024 12:42:54] Failed to download the PowerShell manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='Microsoft.Graph.DeviceManagement...',Version='2.24.0') with status code NotFound
[21/11/2024 12:42:54] No manifest content could be loaded for package Microsoft.Graph.DeviceManagement... on manager PowerShell
[21/11/2024 12:42:55] Failed to download the PowerShell manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='Microsoft.Graph.Devices.Corporat...',Version='2.24.0') with status code NotFound
[21/11/2024 12:42:55] No manifest content could be loaded for package Microsoft.Graph.Devices.Corporat... on manager PowerShell
[21/11/2024 12:42:55] Failed to download the PowerShell manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='Microsoft.Graph.Devices.ServiceA...',Version='2.24.0') with status code NotFound
[21/11/2024 12:42:55] No manifest content could be loaded for package Microsoft.Graph.Devices.ServiceA... on manager PowerShell
[21/11/2024 12:42:57] Icon download attempt at https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/master/documentation/images/graph_color256.png failed with code NotFound
[21/11/2024 12:42:59] Failed to download the PowerShell manifest at Url=https://www.powershellgallery.com/api/v2/Packages(Id='Microsoft.Graph.Identity.Directo...',Version='2.24.0') with status code NotFound
[21/11/2024 12:42:59] No manifest content could be loaded for package Microsoft.Graph.Identity.Directo... on manager PowerShell
[21/11/2024 12:43:05] Found 6 available updates from PowerShell7
[21/11/2024 12:43:16] Found 40 available updates from PowerShell
[21/11/2024 12:47:30] Loaded operation parameters for package id=Microsoft.Graph on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:49:45] Loaded operation parameters for package id=Microsoft.Graph.Applications on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Applications -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:50:36] Loaded operation parameters for package id=Microsoft.Graph.Authentication on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Authentication -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:50:55] Loaded operation parameters for package id=Microsoft.Graph.BackupRestore on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.BackupRestore -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:51:14] Loaded operation parameters for package id=Microsoft.Graph.Bookings on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Bookings -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:51:44] Loaded operation parameters for package id=Microsoft.Graph.Calendar on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Calendar -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:52:05] Loaded operation parameters for package id=Microsoft.Graph.ChangeNotifications on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.ChangeNotifications -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:52:25] Loaded operation parameters for package id=Microsoft.Graph.CloudCommunications on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.CloudCommunications -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:52:42] Loaded operation parameters for package id=Microsoft.Graph.Compliance on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Compliance -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:52:59] Loaded operation parameters for package id=Microsoft.Graph.CrossDeviceExperiences on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.CrossDeviceExperiences -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:53:16] Loaded operation parameters for package id=Microsoft.Graph.DeviceManagement on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.DeviceManagement -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:53:34] Loaded operation parameters for package id=Microsoft.Graph.DeviceManagement.Actions on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.DeviceManagement.Actions -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:53:51] Loaded operation parameters for package id=Microsoft.Graph.DeviceManagement.Administration on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.DeviceManagement.Administration -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:54:14] Loaded operation parameters for package id=Microsoft.Graph.DeviceManagement.Enrollment on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.DeviceManagement.Enrollment -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:54:32] Loaded operation parameters for package id=Microsoft.Graph.DeviceManagement.Functions on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.DeviceManagement.Functions -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:54:51] Loaded operation parameters for package id=Microsoft.Graph.Devices.CloudPrint on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Devices.CloudPrint -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:55:07] Loaded operation parameters for package id=Microsoft.Graph.Devices.CorporateManagement on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Devices.CorporateManagement -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:55:28] Loaded operation parameters for package id=Microsoft.Graph.Devices.ServiceAnnouncement on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Devices.ServiceAnnouncement -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:55:44] Loaded operation parameters for package id=Microsoft.Graph.DirectoryObjects on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.DirectoryObjects -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:56:00] Loaded operation parameters for package id=Microsoft.Graph.Education on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Education -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:56:19] Loaded operation parameters for package id=Microsoft.Graph.Files on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Files -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:56:45] Loaded operation parameters for package id=Microsoft.Graph.Groups on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Groups -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:57:02] Loaded operation parameters for package id=Microsoft.Graph.Identity.DirectoryManagement on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Identity.DirectoryManagement -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:57:20] Loaded operation parameters for package id=Microsoft.Graph.Identity.Governance on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Identity.Governance -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:57:50] Loaded operation parameters for package id=Microsoft.Graph.Identity.Partner on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Identity.Partner -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:58:07] Loaded operation parameters for package id=Microsoft.Graph.Identity.SignIns on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Identity.SignIns -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:58:26] Loaded operation parameters for package id=Microsoft.Graph.Mail on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Mail -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:58:50] Loaded operation parameters for package id=Microsoft.Graph.Notes on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Notes -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:59:06] Loaded operation parameters for package id=Microsoft.Graph.People on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.People -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:59:23] Loaded operation parameters for package id=Microsoft.Graph.PersonalContacts on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.PersonalContacts -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:59:42] Loaded operation parameters for package id=Microsoft.Graph.Planner on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Planner -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 12:59:59] Loaded operation parameters for package id=Microsoft.Graph.Reports on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Reports -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 13:00:16] Loaded operation parameters for package id=Microsoft.Graph.SchemaExtensions on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.SchemaExtensions -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 13:00:34] Loaded operation parameters for package id=Microsoft.Graph.Search on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Search -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 13:00:51] Loaded operation parameters for package id=Microsoft.Graph.Security on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Security -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 13:01:13] Loaded operation parameters for package id=Microsoft.Graph.Sites on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Sites -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 13:01:41] Loaded operation parameters for package id=Microsoft.Graph.Teams on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Teams -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 13:02:14] Loaded operation parameters for package id=Microsoft.Graph.Users on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Users -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 13:02:35] Loaded operation parameters for package id=Microsoft.Graph.Users.Actions on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Users.Actions -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 13:02:52] Loaded operation parameters for package id=Microsoft.Graph.Users.Functions on manager PowerShell and operation Update: Update-Module -Name Microsoft.Graph.Users.Functions -Confirm:$false -Force -Scope CurrentUser
[21/11/2024 13:43:18] Found 0 available updates from .NET Tool
[21/11/2024 13:43:43] Found 6 available updates from PowerShell7
[21/11/2024 13:43:44] Found 0 available updates from PowerShell
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.9.25200
Using Native WinGet helper (COM Api)

——————————————————————————————————————————
```

### Screenshots and videos

![PowerShell meta-module updates](https://github.com/user-attachments/assets/0b045dda-4d65-49a7-aa82-0bb08c53d752)

**Comment by paz** [comment]
Updates are awfully slow unless I ignore them for every Graph module and do those modules outside of UnigetUI.
It's just Powershell which seems to be lacking.
